#!/bin/bash
set -e
. jgb-helper
jgb-build
PATH=$HOME/jgb-build.dir/Debug/x86_64/usr/bin:$HOME/jgb-build.dir/Debug/x86_64/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
export LD_LIBRARY_PATH=$JGB_BUILD_DIR/Debug/$(uname -p)/lib
$@
