#!/bin/bash
# jgb-build
#
# Copyright (C) 2025 Beijing Zohetec Co., Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
set -e

. jgb-helper
jgb_arch=$(uname -p)
jgb_pack_dir=$JGB_BUILD_DIR/pack.dir

help()
{
    echo "[Usage] jgb-pack [-h] [-p ARCH] <package>"
    echo "-h display this help text, then exit"
    echo "-p ARCH 选择目标架构"
    exit 1
} >&2

while getopts  "hp:" opt; do
  case ${opt} in
    h)
      help
      ;;
    p)
      jgb_arch=$OPTARG
      ;;
    ?)
      ;;
  esac
done

shift $((OPTIND - 1))
pk_full_name=$1
pk=$(echo $pk_full_name | cut -d@ -f1)
variant=$(echo $pk_full_name | cut -d@ -f2 -s)
[ -n "$variant" ] && extra_opt="-V $variant"

if [ -z "$pk" ] ; then
    help
fi >&2

[ -n "$JGB_BUILD_DIR" ]
mkdir -p $jgb_pack_dir
pack_tmp_dir=$(mktemp -d $jgb_pack_dir/$pk.XXXXXX)
trap "echo rm $pack_tmp_dir; rm $pack_tmp_dir -rf" EXIT
cd $pack_tmp_dir
for m in Debug Release;
do
    jgb-src -R $pk_full_name
    jgb_pushd $pk
    jgb-build -p${jgb_arch} -t${m} -RP $extra_opt
    jgb_popd
done
