#!/bin/bash
set -e
. jgb-helper
jgb-build
PATH=$HOME/jgb-build.dir/Debug/$(uname -p)/bin:$HOME/jgb-build.dir/Debug/$(uname -p)/sbin:/local/sbin:/local/bin:/sbin:/bin
export LD_LIBRARY_PATH=$JGB_BUILD_DIR/Debug/$(uname -p)/lib
$@
