#!/bin/bash
# jgb-build
#
# Copyright (C) 2025 Beijing Zohetec Co., Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
set -e
. jgb-helper

O_Patch=yes
O_Remove=no

help()
{
    echo "[Usage] jgb-src [-hPR] package"
    echo "-h display this help text, then exit"
    echo "-P Do not apply patches"
    echo "-R Remove the package directory if it exists"
    exit 1
} >&2

while getopts  "hPR" opt; do
  case ${opt} in
    h)
      help
      ;;
    P)
      O_Patch=no
      ;;
    R)
      O_Remove=yes
      ;;
    ?)
      ;;
  esac
done

if [ -f $JGB_BUILD_UPSTREAM_FILE ] ; then
  . $JGB_BUILD_UPSTREAM_FILE
fi

if [ -f $JGB_BUILD_UPSTREAM_FILE.local ] ; then
  . $JGB_BUILD_UPSTREAM_FILE.local
fi

# https://stackoverflow.com/questions/9472871/parse-arguments-after-getopts
shift $((OPTIND - 1))
pk_full_name=$1
pk_full_name=${pk_full_name%/}
package=$(echo $pk_full_name | cut -d@ -f1)
variant=$(echo $pk_full_name | cut -d@ -f2 -s)
suffix_variant=
if [ -n "$variant" ] ; then
  suffix_variant="-${variant}"
fi

if [ -d $package ] ; then
  if [ "$O_Remove" == yes ] ; then
    echo remove $PWD/$package
    rm -rf $package
  else
    echo "$package 目录已存在"
    exit 1
  fi
fi

package_src=${jgb_src[$package]}
if [ -z "$package_src" ] ; then
  echo "not found: $package"
  exit 1
fi >&2

process_zip_src()
{
  package_chksum=${jgb_src_chksum[$package]}
  if [ -n "$package_chksum" ] ; then
    package_chksum_file=$(basename $package_chksum)
    package_chksum_file_cache=$JGB_BUILD_CACHE_DIR/$package_chksum_file
#  else
#    echo "$JGB_BUILD_UPSTREAM_FILE 文件中未指定 jgb_src_chksum[$package]"
  fi >&2

  package_src_file=$(basename $package_src)
  package_src_file_cache=$JGB_BUILD_CACHE_DIR/$package_src_file

  if [ ! -f $package_src_file_cache ] ; then
    mkdir -p $JGB_BUILD_CACHE_DIR
    wget -c $package_src -O $package_src_file_cache
    if [ -n "$package_chksum" ] ; then
      wget -c $package_chksum -O $package_chksum_file_cache
      jgb_pushd .
      cd $JGB_BUILD_CACHE_DIR
      if [[ $package_chksum_file == *".sha256" ]] ; then
        sha256sum -c $package_chksum_file
      else
        echo 不支持的校验文件类型
        exit 1
      fi
      jgb_popd
    fi
  fi

  [ ! -d $package ]
  # 假定：解压缩结果的顶级目录名和包名一致。
  # https://stackoverflow.com/questions/229551/how-to-check-if-a-string-contains-a-substring-in-bash
  if [[ $package_src_file == *".tar.gz" ]] \
     || [[ $package_src_file == *".tar.xz" ]] \
     || [[ $package_src_file == *".tgz" ]] \
     || [[ $package_src_file == *".tar.bz2" ]]; then
    tar xf $package_src_file_cache
  elif [[ $package_src_file == *".zip" ]] ; then
    unzip -q $package_src_file_cache
  elif [[ $package_src_file == *".7z" ]] ; then
    7z x -y $package_src_file_cache
  else
    echo 不支持的文件类型
    exit 1
  fi

  package_config_dir=$JGB_BUILD_CONFIG_DIR/${package}${suffix_variant}
  if [ $O_Patch == yes ] ; then
    jgb_pushd $package
    # https://man7.org/linux/man-pages/man7/glob.7.html
    # https://medium.com/@sisi_hj/use-bash-globs-to-navigate-through-file-system-1b4ea7ecf991
    shopt -s nullglob
    for pf in $package_config_dir/*.patch;
    do
      patch -p1 < $pf
    done
    jgb_popd >/dev/null
  else
    echo "已跳过应用补丁"
  fi

  if [ -x $package_config_dir/local-build ] || [ -h $package_config_dir/local-build ]; then
    ln -vs $package_config_dir/local-build $package
  fi
}

process_git_src()
{
  [ ! -d $package ]
  git clone $package_src
  cd $package
  if [ -n "$variant" ] ; then
    #git fetch --tags
    #TODO：如果存在同名的 branch 和 tag，该如何处理？
    git checkout $variant || {
        echo "variant not found: $variant"
        exit 1
    }
  fi
}

if [[ $package_src == *".zip" ]] \
 || [[ $package_src == *".tar.gz" ]] \
 || [[ $package_src == *".tar.xz" ]] \
 || [[ $package_src == *".tgz" ]] \
 || [[ $package_src == *".tar.bz2" ]] \
 || [[ $package_src == *".7z" ]] \
 ; then
  process_zip_src
elif [[ $package_src == *".git" ]] ; then
  process_git_src
else
  echo "不支持的源包类型: $package_src"
  exit 1
fi

echo 获取源码：$package
echo 完成
