#!/bin/bash
# jgb-build
#
# Copyright (C) 2025 Beijing Zohetec Co., Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
set -e

. jgb-helper
jgb_arch=$(uname -p)

help()
{
    echo "[Usage] jgb-install [-f FILE] [-h] [-p ARCH] <package>"
    echo "-f FILE 指定包含包列表的 JSON 文件"
    echo "-h display this help text, then exit"
    echo "-p ARCH 选择目标架构"
    exit 1
} >&2

while getopts  "f:hp:" opt; do
  case ${opt} in
    f)
      jgb_list_file=$OPTARG
      ;;
    h)
      help
      ;;
    p)
      jgb_arch=$OPTARG
      ;;
    ?)
      ;;
  esac
done

install_package()
{
    local pk_full_name=$1
    local pk=$(echo $pk_full_name | cut -d@ -f1)
    local variant=$(echo $pk_full_name | cut -d@ -f2 -s)
    local suffix_variant=
    if [ -n "$variant" ] ; then
      suffix_variant="_${variant}"
    fi
    local pk_file=${pk}${suffix_variant}.tar.gz
    for m in Debug Release ;
    do
        pk_file_path=${JGB_BUILD_DIR}/local/packages/$m/$jgb_arch/$pk/$pk_file
        if [ -f $pk_file_path ] ; then
          notify_msg="[local]"
        else
          pk_file_path=${JGB_BUILD_DIR}/dist/packages/$m/$jgb_arch/$pk/$pk_file
        fi
        if [ ! -f $pk_file_path ] ; then
          echo "not found: $pk [ $pk_file_path ]"
          exit 1
        fi
        echo "extract: $pk_full_name $notify_msg"
        local dest_dir=${JGB_BUILD_DIR}/$m/$jgb_arch
        mkdir -p $dest_dir
        tar -C $dest_dir -xf $pk_file_path
    done
}

if [ -n "$jgb_list_file" ] ; then
  if [ -f "$jgb_list_file" ] ; then
      x=0
      while true;
      do
          pk_full_name=$(jq -r .packages[$x] $jgb_list_file)
          if [ $pk_full_name != null ] ; then
              install_package $pk_full_name
              ((++x))
          else
              break
          fi
      done
  fi
fi

shift $((OPTIND - 1))
for pk_fn in "$@";
do
    install_package $pk_fn
done
