#!/bin/bash
# jgb-build
#
# Copyright (C) 2025 Beijing Zohetec Co., Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
set -e
. jgb-helper

jgb_arch=$(uname -p)

help()
{
    echo "[Usage] jgb-status [-h] [-p ARCH]"
    echo "-h display this help text, then exit"
    echo "-p ARCH 选择目标架构"
    exit 1
} >&2

while getopts  "hp:" opt; do
  case ${opt} in
    h)
      help
      ;;
    p)
      jgb_arch=$OPTARG
      ;;
    ?)
      ;;
  esac
done

LANG=C
shopt -s nullglob

output_file=$(mktemp /tmp/jgb-status.XXXX)
trap 'rm -f "output_file"' EXIT
count=0

for dir in ./*/;
do
  pushd $dir > /dev/null
  if [ -d .git ] ; then
    count=$((count+1))
    if [ $count -eq 1 ] ; then
      echo Dir,toTrack,toCommit,toPush,toPack >> $output_file
    fi
    pk=$(basename $PWD)
    echo -n $pk, >> $output_file
    to_track='-'
    to_commit='-'
    to_push='-'
    to_pack=Y

    git status | grep -q '^Changes to be committed:\|^Changes not staged for commit' && to_commit=Y
    git status | grep -q '^Untracked files:' && to_track=Y
    git status | grep -q '^Your branch is ahead of' && to_push=Y

    if [ -n "$jgb_arch" ] ; then
      pk_info_file=$pk.info
      pk_info_file_path=${JGB_BUILD_DIR}/dist/packages/Release/$jgb_arch/$pk/$pk_info_file
      if [ -f $pk_info_file_path ] ; then
        pk_commit_id=$(jq -r .commit $pk_info_file_path)
        commit_id=$(git rev-parse HEAD 2>/dev/null)
        if [ "$commit_id" == "$pk_commit_id" ] ; then
          to_pack='-'
        fi
      fi
    fi
    echo $to_track,$to_commit,$to_push,$to_pack >> $output_file
  fi
  popd > /dev/null
done
#cat $output_file
column -s, -t < $output_file
