#!/bin/bash
set -e

. jgb-helper
jgb_arch=$(uname -p)

help()
{
    echo "[Usage] jgb-push [-cdh] [-p ARCH] package"
    echo "-c 清除指定的 ARCH 或者 package"
    echo "-d DATE 指定包的日期，默认今天"
    echo "-h display this help text, then exit"
    echo "-p ARCH 选择目标架构"
    echo "-r 在 dist 目录中恢复软链接指向指定日期的包"
    exit 1
} >&2

while getopts  "cd:hp:r" opt; do
  case ${opt} in
    c)
      clean=yes
      ;;
    d)
      jgb_date=$OPTARG
      ;;
    h)
      help
      ;;
    p)
      jgb_arch=$OPTARG
      ;;
    r)
      revert=yes
      ;;
    ?)
      ;;
  esac
done

shift $((OPTIND - 1))
pk_full_name=$1
pk=$(echo $pk_full_name | cut -d@ -f1)
variant=$(echo $pk_full_name | cut -d@ -f2 -s)
[ -n "$variant" ] && extra_opt="-V $variant"

if [ -z "$pk" ] ; then
  if [ "$clean" == yes ] && [ -n "$jgb_arch" ] ; then
    for m in Debug Release;
    do
        pack_dir=${JGB_BUILD_DIR}/local/packages/$m/${jgb_arch}
        echo remove $pack_dir
        rm -rf $pack_dir
    done
    exit 0
  else
    help
  fi
fi

if [ -z "$jgb_date" ] ; then
    jgb_date=$(date +%Y%m%d)
fi

for m in Debug Release;
do
    src_dir=${JGB_BUILD_DIR}/local/packages/$m/${jgb_arch}/${pk}
    dst_dir=${JGB_BUILD_DIR}/dist/packages/$m/${jgb_arch}/${pk}
    package_file_name=${pk}${x_variant}-$(date +%Y%m%d).tar.gz
    src_file_path=$src_dir/$package_file_name
    dst_file_path=$dst_dir/$package_file_name
    package_file_name_short=${pk}${x_variant}.tar.gz
    if [ "$clean" == yes ] ; then
        rm -vf $src_file_path
        rm -vf $src_dir/$package_file_name_short
    elif [ "$revert" == yes ] ; then
        if [ -f $dst_file_path ] ; then
            ln -vsf $package_file_name $dst_dir/$package_file_name_short
        else
            echo "not found: $pk_full_name [$dst_file_path]"
            exit 1
        fi
    else
        if [ ! -f $src_file_path ] ; then
            echo "not found: $pk_full_name [$src_file_path]"
            exit 1
        fi
        mkdir -p $dst_dir
        /bin/cp -v $src_file_path $dst_dir
        ln -vsf $package_file_name $dst_dir/$package_file_name_short
    fi
done
